# Generated by Django 3.0.5 on 2020-06-01 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'BaseEmpleado',
                'verbose_name_plural': 'BaseEmpleados',
            },
        ),
        migrations.CreateModel(
            name='CargoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cargo Grupo',
                'verbose_name_plural': 'Cargos Grupo',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_vacaciones', models.DateField()),
                ('fecha_fin_vacaciones', models.DateField()),
                ('periodos', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('A', 'Aceptado'), ('C', 'Cancelado'), ('E', 'Espera')], default='E', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='api.Ciudad')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('empalme', models.PositiveIntegerField()),
                ('horario', models.CharField(choices=[('A', 'lunes - Viernes'), ('B', 'Lunes - Sabado')], max_length=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='api.CargoGrupo')),
            ],
        ),
        migrations.CreateModel(
            name='Supernumerario',
            fields=[
                ('baseempleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseEmpleado')),
                ('cargo', models.ManyToManyField(blank=True, related_name='supernumerarios', to='api.Cargo')),
                ('ciudad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supernumerarios', to='api.Ciudad')),
            ],
            options={
                'verbose_name': 'Supernumerario',
                'verbose_name_plural': 'Supernumerarios',
            },
            bases=('api.baseempleado', models.Model),
        ),
        migrations.CreateModel(
            name='Historicosolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_inicio_vacaciones', models.DateField()),
                ('sup_fin_vacaciones', models.DateField()),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicosolicitudes', to='api.Cargo')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicosolicitudes', to='api.Oficina')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historicosolicitudes', to='api.Solicitud')),
                ('supernumerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicosolicitudes', to='api.Supernumerario')),
            ],
            options={
                'verbose_name': 'Historico Solicitud',
                'verbose_name_plural': 'Historicos Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('baseempleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseEmpleado')),
                ('fecha_ingreso', models.DateField()),
                ('periodos_causados', models.PositiveIntegerField()),
                ('cargo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='api.Cargo')),
                ('oficina', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='api.Oficina')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
            bases=('api.baseempleado', models.Model),
        ),
    ]
