# Generated by Django 3.0.5 on 2020-06-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cargo_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargoGrupo',
        ),
    ]
